[package]
name = "blis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blis-sys = "0.1.2"
reborrow = "0.2.0"
